apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: jenkins
        image: jenkinsci/blueocean:lts
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 50000
        volumeMounts: 
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true 
        - name: docker
          mountPath: /usr/sbin/docker
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-home 
        hostPath:
          path: /data/jenkins_home
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: docker
        hostPath:
          path: /usr/bin/docker
      nodeSelector:
        disktype: hdd
